name: 新项目
description: 做完需求分析后，由 idea2app 工程师创建新项目的代码库
title: "【项目】"
labels:
  - project
assignees:
  - TechQuery

body:
  - type: input
    id: discussion_link
    attributes:
      label: 讨论链接
      description: https://github.com/orgs/idea2app/discussions/categories/ideas 中的讨论帖链接
      placeholder: 形如 https://github.com/orgs/idea2app/discussions/3
    validations:
      required: true

  - type: dropdown
    id: desktop_template
    attributes:
      label: 桌面端模板
      description: 桌面端、移动端、服务端模板至少选一个
      options:
        - https://github.com/EasyWebApp/WebCell-scaffold
        - https://github.com/EasyWebApp/WebCell-dashboard
        - https://github.com/idea2app/React-MobX-Bootstrap-ts
        - https://github.com/idea2app/React-MobX-MUI-ts
        - https://github.com/idea2app/React-MobX-Ant-Design-ts
        - https://github.com/idea2app/Next-Bootstrap-ts
        - https://github.com/idea2app/Lark-Next-Bootstrap-ts
        - https://github.com/idea2app/Vue-MobX-Prime-ts

  - type: dropdown
    id: mobile_template
    attributes:
      label: 移动端模板
      description: 桌面端、移动端、服务端模板至少选一个
      options:
        - https://github.com/EasyWebApp/WebCell-mobile
        - https://github.com/idea2app/Taro-Vant-MobX-ts
        - https://github.com/idea2app/Vue3-Taro-Vant-ts
        - https://github.com/idea2app/uniapp-uview-ts

  - type: dropdown
    id: server_template
    attributes:
      label: 服务端模板
      description: 桌面端、移动端、服务端模板至少选一个
      options:
        - https://github.com/idea2app/Deno-quick-start
        - https://github.com/idea2app/REST-Node-ts
        - https://github.com/idea2app/Vercel-Node-serverless
        - https://github.com/idea2app/Strapi-PNPM-Docker-ts
        - https://github.com/idea2app/Kotlin-Spring-Boot
        - https://github.com/idea2app/ThinkPHP-scaffold

  - type: dropdown
    id: reward_currency
    attributes:
      label: 悬赏币种
      options:
        - "USD $"
        - "CAD C$"
        - "AUD A$"
        - "GBP £"
        - "EUR €"
        - "CNY ¥"
        - "HKD HK$"
        - "TWD NT$"
        - "SGD S$"
        - "KRW ₩"
        - "JPY ¥"
        - "INR ₹"
        - "UAH ₴"
    validations:
      required: true

  - type: input
    id: reward_amount
    attributes:
      label: 悬赏金额
    validations:
      required: true

  - type: textarea
    id: remark
    attributes:
      label: 备注
